name: Android CI

on:
  push:
    branches: master
  pull_request_target:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Gradle Assemble 
      run: ./gradlew assemble
    - name: Build with Gradle
      run: ./gradlew build
